### ISSUE TITLE
FYI disclosed information.

### ISSUE THREAD

**Issue by Landrash** [CiquattroFPV/Homeassistant-Example-Config#1]
Looking trough your examples.
There's quite a few places where information is left where in other places it's redacted.

Your name: N***
Other person 1: M****
Other person 1 name: M****

Would be a tad hard to redact without changing names of your notification services and device trackers but worth mentioning.

**Comment by CiquattroFPV** [comment]
Yes.. Thanks for the info.. but it's oka.. the important is the latitude and longitude information..

**Comment by CiquattroFPV** [comment]
I have renamed the file.. can you check if all it's okay now?

thanks

**Comment by Landrash** [comment]
There's still some places where information can be seen such as the who cooks input select.
Just wanted you to be aware of it :)
